---
- name: Initial bootstrappin
  hosts: localhost
  connection: local
  become: true
    #  roles:
    #    - base
  vars_files:
    - vars/initial.yml
    - vars/secret

  pre_tasks:
  - name: Update ubuntu repository index and packages
    tags: always
    apt: 
      update_cache: yes
      name: "*"
      state: latest
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  - name: Update arch repository index and packages
    tags: always
    community.general.pacman: 
      update_cache: yes
      upgrade: yes
    changed_when: false
    when: ansible_distribution == "Archlinux"

  - name: Make sure we have a 'sudo' group
    ansible.builtin.group:
      name: sudo
      state: present


  - name: Add ssh keys
    authorized_key:
      user: veeson
      state: present
      key: "{{ item }}"
    with_file:
      - vars/public_keys/development
  
  roles:
    - base
