---
- name: Initial bootstrappin
  hosts: localhost
  connection: local
  become: true
  vars_files:
    - vars/initial.yml
    - vars/secret

  pre_tasks:
  - name: Update apt cache
    apt: update_cache=yes

  - name: Update all installed packages
    ansible.builtin.apt:
      name: "*"
      state: latest

  - name: Make sure we have a 'sudo' group
    ansible.builtin.group:
      name: sudo
      state: present

  - name: Create user with sudo privileges
    user: 
      name: "{{ username }}"
      password: "{{ password | password_hash('sha512', password_salt) }}"
      shell: /bin/bash 
      groups: sudo 
      append: yes 
      generate_ssh_key: yes 
      create_home: true
      ssh_key_bits: 2048 
      update_password: on_create
      state: present

  tasks:
  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu jammy stable
      state: present

  - name: install packages
    apt:
      pkg:
       - apt-transport-https
       - ca-certificates
       - curl
       - software-properties-common
       - python3-pip
       - virtualenv
       - python3-setuptools
       - tmux
       - neovim
       - golang
       - ansible
       - fzf
       - ripgrep
       - zip
       - docker-ce
       - docker-ce-cli
       - containerd.io
       - docker-compose
      state: latest
      update_cache: true


