---
  - name: install arch packages
    community.general.pacman: 
      name:
        - sxhkd
        - kitty
        - brave-browser
        - unclutter
        - mpv
        - picom
        - python-pip
        - python-pywal
        - feh
        - dunst
        - i3-wm
        - virt-viewer
        - sxiv
        - zathura
        - zathura-pdf-poppler
        - zathura-epud
        - yad
      state: latest
      update_cache: true

  - name: setup i3 dotfiles 
    import_tasks: links/i3-wm-dotfiles.yml
