---
  - name: install arch packages
    community.general.pacman: 
      name:
        - sxhkd
        - kitty
        - brave-browser
        - unclutter
        - mpv
        - picom
      state: latest
      update_cache: true

  - name: setup i3 dotfiles 
    import_tasks: links/i3-wm-dotfiles.yml
