#Workstation main config 

  - name: General workstation setup
    tags: general-station
    import_tasks: workstation_env.yml

  - name: development workstation setup
    tags: 
      - develop-station
      - never
    import_tasks: development_env.yml

  - name: projects_docs_notes setup
    tags: 
      - solo-workstation-task
      - never
    import_tasks: links/projects_docs_scripts.yml

  - name: xorg workstation setup
    tags: 
      - xorg-station 
      - never
    import_tasks: xorg_workstation_env.yml

  - name: I3 workstation setup
    tags: 
      - i3-station 
      - never
    import_tasks: i3_workstation_env.yml

  - name: wayland workstation setup
    tags: 
      - wayland-station 
      - never
    import_tasks: wayland_workstation_env.yml
