#Workstation main config 

  - name: general workstation setup
    become_user: veeson
    tags: general-station
    import_tasks: workstation_env.yml

  - name: development workstation setup
    tags: 
      - develop-station
      - never
    import_tasks: development_env.yml

  - name: xorg workstation setup
    become_user: veeson
    tags: 
      - xorg-station 
      - never
    import_tasks: xorg_workstation_env.yml

  - name: wayland workstation setup
    become_user: veeson
    tags: 
      - wayland-station 
      - never
    import_tasks: wayland_workstation_env.yml
