---
  - name: install arch packages wayland
    community.general.pacman: 
      name:
        - rofi
        - ttf-firacode-nerd
        - noto-fonts
        - noto-fonts-emoji
        - ttf-linux-libertine
       #- sxhkd
        - kitty
        # - brave-browser
        - unclutter
        - mpv
        - python-pip
        - python-pywal
        - feh
        - dunst
        - hyprland
        - virt-viewer
        - sxiv
        - zathura
        - zathura-pdf-poppler
        - brightnessctl
        # - zathura-epud
        - yad
      state: latest
      update_cache: true

  - name: setup wayland dotfiles 
    vars:
      path: /home/veeson/sync-store/Sync_Ref/Config_files/Dotfiles
    import_tasks: links/hyprland-wm-dotfiles.yml
