---
  - name: Create a .config
    ansible.builtin.file:
      path: /home/veeson/.config
      state: directory
      mode: '0755'

  - name: Create a zsh history
    block:
      - name: create zsh directory
        ansible.builtin.file:
          path: /home/veeson/.cache/zsh
          state: directory
          mode: '0755'

      - name: create zsh_history file
        ansible.builtin.file:
          path: /home/veeson/.cache/zsh/.zsh_history
          state: touch
    become_user: veeson
    become: true

  - name: syncthing workstation setup
    import_tasks: sync_tasks.yml

  - name: Installing apt general workstation packages
    ansible.builtin.apt:
      name: 
        - sl
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

  - name: Installing pacman general workstation packages
    community.general.pacman:
      name: 
        - sl
      state: latest
    when: ansible_distribution == "Archlinux"
