
  - name: ln ct Notesbooks
    tags: ln-ct-notebooks
    ansible.builtin.file:
      src: "{{ path }}/Document_and_Notes/Document_Achives/Notebooks"
      dest: /home/veeson/Notebooks
      state: link

  - name: ln ct  Documents
    tags: ln-ct-documents
    ansible.builtin.file:
      src: "{{ path }}/Document_and_Notes/Document_Achives/Documents"
      dest: /home/veeson/Documents
      state: link

  - name: ln ct Projects
    tags: ln-ct-projects
    ansible.builtin.file:
      src: "{{ path }}/Projects_Src/Projects"
      dest: /home/veeson/Projects
      state: link

  - name: ln ct Tools
    tags: ln-ct-tools
    ansible.builtin.file:
      src: "{{ path }}/Sync_Ref/Code_Achives/Tools"
      dest: /home/veeson/Tools
      state: link
