---

  - name: Create a .config
    ansible.builtin.file:
      path: /home/veeson/.config
      state: directory
      mode: '0755'

  - name: local-ct Sync zshrc
    tags: ct-local-config
    ansible.builtin.file:
      src: "{{ path }}/zsh/.zshrc"
      dest: /home/veeson/.zshrc
      state: link

  - name: local-ct Sync zsh
    tags: ct-local-config
    ansible.builtin.file:
      src: "{{ path }}/zsh"
      dest: /home/veeson/.config/zsh
      state: link

  - name: local-ct Env
    tags: ct-local-config
    ansible.builtin.file:
      src: "{{ path }}/env"
      dest: /home/veeson/.config/env
      state: link

  - name: Create a zsh history
    ansible.builtin.file:
      path: /home/veeson/.cache/zsh
      state: directory
      mode: '0755'

  - name: create zsh_history file
    ansible.builtin.file:
      path: /home/veeson/.cache/zsh/.zsh_history
      state: touch

  - name: local-ct Sync lf
    tags: ct-local-config
    ansible.builtin.file:
      src: "{{ path }}/lf"
      dest: /home/veeson/.config/lf
      state: link

  - name: local-ct Sync tmux
    tags: ct-local-config
    ansible.builtin.file:
      src: "{{ path }}/.tmux.conf"
      dest: /home/veeson/.tmux.conf
      state: link

  - name: local-ct Sync nvim
    tags: ct-local-config
    ansible.builtin.file:
      src: "{{ path }}/nvim"
      dest: /home/veeson/.config/nvim
      state: link
  
