# base play for ssh, user creation and setup for ansible


  - name: Make sure we have '/home/veeson' 
    ansible.builtin.user:
      name: veeson
      home: /home/veeson
      state: present

  - name: Sync ct local configs
    become_user: veeson
    become: true
    tags: ct-local-server
    import_tasks: server_configs.yml
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
        
