# base play for ssh, user creation and setup for ansible

  - name: Make sure we have '/home/veeson' 
    ansible.builtin.user:
      name: veeson
      home: /home/veeson
      state: present
    register: veeson_home
    ignore_errors: True

      #  - block:
  - name: Sync ct local configs
    vars:
        path: /mnt/syncthing-files/Sync_Ref/Config_files/
    become_user: veeson
    become: true
    tags: ct-local-server
    import_tasks: ct_server_configs.yml
    when: ansible_virtualization_type == "lxc" 
 
  - name: Server nfs setups
    tags: vm-nfs-local-server
    import_tasks: server_nfs.yml
    when: ansible_virtualization_type == "kvm" 
 
  - name: Sync kvm local configs
    become_user: veeson
    become: true
    tags: vm-local-server
    import_tasks: vm_server_configs.yml
    when: ansible_virtualization_type == "kvm" 
 
  - name: Sync projects and scripts
    become_user: veeson
    become: true
    tags: 
      - vm-local-docs
      - never
    import_tasks: projects_scripts_vm.yml
 
      #    when: veeson_home.state  == "present"
 
