---
  - name: local-ct Sync zshrc
    tags: ct-local-config
    ansible.builtin.file:
      src: /mnt/sync/Sync_Ref/Config_files/Dotfiles/zsh/.zshrc
      dest: /home/veeson/.zshrc
      owner: veeson
      group: veeson
      state: link

  - name: local-ct Sync zsh
    tags: ct-local-config
    ansible.builtin.file:
      src: /mnt/sync/Sync_Ref/Config_files/Dotfiles/zsh
      dest: /home/veeson/.config/zsh
      owner: veeson
      group: veeson
      state: link

  - name: Create a zsh history
    ansible.builtin.file:
      path: /home/veeson/.cache/zsh
      state: directory
      mode: '0755'

  - name: create zsh_history file
    ansible.builtin.file:
      path: /home/veeson/.cache/zsh/.zsh_history
      state: file
      state: present

  - name: local-ct Sync lf
    tags: ct-local-config
    ansible.builtin.file:
      src: /mnt/sync/Sync_Ref/Config_files/Dotfiles/zsh/lf
      dest: /home/veeson/.config/lf
      owner: veeson
      group: veeson
      state: link


  - name: local-ct Sync tmux
    tags: ct-local-config
    ansible.builtin.file:
      src: /mnt/sync/Sync_Ref/Config_files/Dotfiles/.tmux.conf
      dest: /home/veeson/.tmux.conf
      owner: veeson
      group: veeson
      state: link

  - name: local-ct Sync nvim
    tags: ct-local-config
    ansible.builtin.file:
      src: /mnt/sync/Sync_Ref/Config_files/Dotfiles/nvim
      dest: /home/veeson/.config/nvim
      owner: veeson
      group: veeson
      state: link
  
