---
  - name: Create a .config
    ansible.builtin.file:
      path: /home/veeson/.config
      state: directory
      mode: '0755'

  - name: Mount configs-backup-store
    ansible.posix.mount:
      src: 192.168.0.44:/mnt/configs-backups-store
      path: /mnt/configs-backups-store
      opts: defaults
      state: mounted
      fstype: nfs

  - name: local-vm Sync zshrc
    tags: vm-local-config
    ansible.builtin.file:
      src: /mnt/configs-backups-store/syncthing-files/Sync_Ref/Config_files/Dotfiles/zsh/.zshrc
      dest: /home/veeson/.zshrc
      state: link

  - name: local-vm Sync zsh
    tags: vm-local-config
    ansible.builtin.file:
      src: /mnt/configs-backups-store/syncthing-files/Sync_Ref/Config_files/Dotfiles/zsh
      dest: /home/veeson/.config/zsh
      state: link

  - name: local-vm Env
    tags: vm-local-config
    ansible.builtin.file:
      src: /mnt/configs-backups-store/syncthing-files/Sync_Ref/Config_files/Dotfiles/env
      dest: /home/veeson/.config/env
      state: link

  - name: local-vm Create a zsh history
    tags: vm-local-config
    ansible.builtin.file:
      path: /home/veeson/.cache/zsh
      state: directory
      mode: '0755'

  - name: local-vm vm create zsh_history file
    tags: vm-local-config
    ansible.builtin.file:
      path: /home/veeson/.cache/zsh/.zsh_history
      state: touch

  - name: local-vm Sync lf
    tags: vm-local-config
    ansible.builtin.file:
      src: /mnt/configs-backups-store/syncthing-files/Sync_Ref/Config_files/Dotfiles/lf
      dest: /home/veeson/.config/lf
      state: link

  - name: local-vm Sync tmux
    tags: vm-local-config
    ansible.builtin.file:
      src: /mnt/configs-backups-store/syncthing-files/Sync_Ref/Config_files/Dotfiles/.tmux.conf
      dest: /home/veeson/.tmux.conf
      state: link

  - name: local-vm Sync nvim
    tags: vm-local-config
    ansible.builtin.file:
      src: /mnt/configs-backups-store/syncthing-files/Sync_Ref/Config_files/Dotfiles/nvim
      dest: /home/veeson/.config/nvim
      state: link
  
