# arch base packages, to be tested

  - name: update arch
    community.general.pacman: 
      update_cache: yes
      upgrade: yes
    changed_when: false


  - name: install arch packages
    community.general.pacman: 
      name:
       - curl
       - python-pip
       - python-setuptools
       - tmux
       - neovim
       - go
       - fzf
       - ripgrep
       - docker-compose
       - docker
       - lf 
       - openssh
      state: latest
      update_cache: true
