# debian base packages 

  - name: Fetch nodejs PPA
    ansible.builtin.uri:
      url: https://deb.nodesource.com/setup_18.x 
      return_content: yes
    register: nodejs_installer
  
  - name: Run nodejs installer
    ansible.builtin.shell:
      cmd: sh -s -- -y
      stdin: "{{ nodejs_installer.content }}"
  
  - name: install base apt packages
    apt:
      pkg:
       - apt-transport-https
       - ca-certificates
       - curl
       - software-properties-common
       - python3-pip
       - virtualenv
       - python3-setuptools
       - tmux
       - neovim
       - golang
       - ansible
       - fzf
       - ripgrep
       - zip
       - zsh
       - gnupg  
      state: latest
      update_cache: true
