# debian base packages 

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu jammy stable
      state: present

  - name: install packages
    apt:
      pkg:
       - apt-transport-https
       - ca-certificates
       - curl
       - software-properties-common
       - python3-pip
       - virtualenv
       - python3-setuptools
       - tmux
       - neovim
       - golang
       - ansible
       - fzf
       - ripgrep
       - zip
       - docker-ce
       - docker-ce-cli
       - containerd.io
       - docker-compose
      state: latest
      update_cache: true
