# debian base packages 

  - name: install apt packages
    apt:
      pkg:
       - apt-transport-https
       - ca-certificates
       - curl
       - software-properties-common
       - python3-pip
       - virtualenv
       - python3-setuptools
       - tmux
       - neovim
       - golang
       - ansible
       - fzf
       - ripgrep
       - zip
       - zsh
       - gnupg  
      state: latest
      update_cache: true

