# base play for ssh, user creation and setup for ansible

#  become: true
#  tasks:
#    - name: create veeson user
#      user:
#        name: developer
#        create_home: true
#        shell: /bin/bash
#        groups: admin

  - name: Install base apt packages
    import_tasks: debian.yml
    tags: apt-base-pkg
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

  - name: Install base arch packages
    import_tasks: arch.yml
    tags: arch-base-pkg
    when: ansible_distribution == "Archlinux"
