# base play for ssh, user creation and setup for ansible

#  become: true
#  tasks:
#    - name: create veeson user
#      user:
#        name: developer
#        create_home: true
#        shell: /bin/bash
#        groups: admin
#        

  - name: Create user with sudo privileges
    user: 
      name: "{{ username }}"
      password: "{{ password | password_hash('sha512', password_salt) }}"
      shell: /bin/bash 
      groups: sudo 
      append: yes 
      generate_ssh_key: yes 
      create_home: true
      ssh_key_bits: 2048 
      update_password: on_create
      state: present

  - name: Make sure we have a 'sudo' group
    ansible.builtin.group:
      name: sudo
      state: present

  - name: Add ssh keys
    authorized_key:
      user: veeson
      state: present
      key: "{{ pub_ssh }}"

  - name: Install base apt packages
    import_tasks: debian.yml
    tags: apt-base-pkg
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

  - name: Install base arch packages
    import_tasks: arch.yml
    tags: arch-base-pkg
    when: ansible_distribution == "Archlinux"
