# base play for ssh, user creation and setup for ansible


  - name: Make sure we have a 'sudo' group
    ansible.builtin.group:
      name: sudo
      state: present

  - name: Install base apt packages
    tags: apt-base-pkg
    import_tasks: debian.yml
    when: ansible_os_family == "Debian"
    # when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" or ansible_distribution == "Pop!_OS"
        
  - name: Install base apt packages
    import_tasks: repo_utils.yml
    tags: apt-repo-pkg
    when: ansible_os_family == "Debian"
    # when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" or ansible_distribution == "Pop!_OS"

  - name: Install base arch packages
    import_tasks: arch.yml
    when: ansible_distribution == "Archlinux"

  - name: Create user with sudo privileges
    user: 
      name: "{{ username }}"
      password: "{{ password | password_hash('sha512', password_salt) }}"
      shell: /bin/zsh 
      groups: sudo,docker
      append: yes 
      generate_ssh_key: yes 
      create_home: true
      ssh_key_bits: 2048 
      update_password: on_create
      state: present

  - name: Add ssh keys
    tags: ssh-pubkey
    authorized_key:
      user: veeson
      state: present
      key: "{{ pub_ssh }}"
