
  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu jammy stable
      state: present

  - name: install apt packages
    apt:
      pkg:
       - docker-ce
       - docker-ce-cli
       - containerd.io
       - docker-compose

  - name: Installing and adding lf
    script: ../../../scripts/lf_install.sh
