
  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
      state: present

  - name: install apt packages
    apt:
      pkg:
       - docker-ce
       - docker-ce-cli
       - containerd.io
       - docker-compose

# This can be changed to use local user:veeson, thus path in the script will be different
# The script should be written as ansible tasks, so as to keep idempotent
  - name: Installing and adding lf
    tags: apt-lf-pkg
    script: ../../../scripts/lf_install.sh
